apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "promlens.fullname" . }}
  labels:
    app: {{ template "promlens.name" . }}
    chart: {{ template "promlens.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "promlens.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "promlens.name" . }}
    spec:
      containers:
      - name: promlens
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
        args:
          {{- if .Values.config.shared_links.gcs.enabled }}
          - --shared-links.gcs.bucket={{ .Values.config.shared_links.gcs.bucket }}
          {{- end }}
          {{- if .Values.config.shared_links.sql.enabled }}
          - --shared-links.sql.driver={{ .Values.config.shared_links.sql.driver }}
          - --shared-links.sql.retention={{ .Values.config.shared_links.sql.retention }}
          {{- if not .Values.config.shared_links.sql.create_tables }}
          - --no-shared-links.sql.create-tables
          {{- end }}
          {{- end }}
          {{- if .Values.config.grafana.enabled }}
          - --grafana.url={{ .Values.config.grafana.url }}
          - --grafana.api-token={{ .Values.config.grafana.api_token }}
          {{- end }}
          {{- if .Values.config.web.external_url }}
          - --web.external-url={{ .Values.config.web.external_url }}
          {{- end }}
          {{- if .Values.config.web.default_prometheus_url }}
          - --web.default-prometheus-url={{ .Values.config.web.default_prometheus_url }}
          {{- end }}
          - --log.level={{ .Values.config.log.level }}
          - --log.format={{ .Values.config.log.format }}
          - --license.key={{ .Values.config.license_key }}

{{ if .Values.config.shared_links.gcs.enabled }}
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secret-files/gcs-cred.json
        volumeMounts:
        - mountPath: /var/secret-files
          name: secret-files
      volumes:
        - name: secret-files
          secret:
            defaultMode: 420
            secretName: promlens-secrets
{{ end }}
{{ if .Values.config.shared_links.sql.enabled }}
        env:
          - name: PROMLENS_SHARED_LINKS_DSN
            valueFrom:
              secretKeyRef:
                name: promlens-secrets
                key: sql-dsn
{{ end }}
