{{- if or .Values.config.shared_links.gcs.enabled .Values.config.shared_links.sql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: promlens-secrets
  labels:
    app: {{ template "promlens.name" . }}
    chart: {{ template "promlens.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gcs-cred.json: {{ .Values.config.shared_links.gcs.storage_account | default "" | quote }}
  sql-dsn: {{ .Values.config.shared_links.sql.dsn | b64enc | default "" | quote }}
{{- end}}
